```{r}
library(ISLR)
library(corrplot)
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(caret)
library(car)
library(e1071)
```

```{r}
train=read.csv("train.csv",stringsAsFactors = FALSE,header = T )
test=read.csv("test.csv",stringsAsFactors = FALSE,header = T )
apply(train,2,function(x)sum(is.na(x)))
apply(test,2,function(x)sum(is.na(x)))
test$y=NA
train$data='train'
test$data='test'
all_data=rbind(train,test)
apply(all_data,2,function(x)sum(is.na(x)))
final=round(prop.table(table(all_data$job,all_data$y),1)*100,1)
final
```
```{r}
ggplot(all_data, aes(x=age, fill=marital)) + geom_histogram(binwidth = 2, alpha=0.7) +facet_grid(cols = vars(y))
ggplot(all_data, aes(age, duration)) +geom_point() +facet_grid(cols = vars(y))
ssss=all_data %>% select(duration, campaign, age)
pairs(ssss)
```


```{r}


rrrr=addmargins(final,2) 
sort(rrrr[,1])
all_data=all_data %>% mutate(job_1=as.numeric(job %in% c("self-employed","unknown","technician")),job_2=as.numeric(job %in% c("services","housemaid","entrepreneur")), job_3=as.numeric(job %in% c("management","admin")),job_4=as.numeric(job=="student"), job_5=as.numeric(job=="retired"), job_6=as.numeric(job=="unemployed")) %>% 
select(-job)
all_data=all_data %>% mutate(divorced=as.numeric(marital %in% c("divorced")), single=as.numeric(marital %in% c("single")) ) %>% 
select(-marital)
glimpse(all_data)
all_data=all_data %>% mutate(edu_primary=as.numeric(education %in% c("primary")),edu_sec=as.numeric(education %in% c("secondary")),edu_tert=as.numeric(education %in% c("tertiary"))) %>% 
select(-education)
all_data$default=as.numeric(all_data$default=="yes")
all_data$housing=as.numeric(all_data$housing=="yes")
all_data$loan=as.numeric(all_data$loan=="yes")
all_data=all_data %>% mutate(co_cellular=as.numeric(contact %in% c("cellular")),co_tel=as.numeric(contact %in% c("telephone"))) %>% 
select(-contact)
```
```{r}
all_data=all_data %>% mutate(poc_success=as.numeric(poutcome %in% c("success")),poc_failure=as.numeric(poutcome %in% c("failure")),poc_other=as.numeric(poutcome %in% c("other")))%>% 
select(-poutcome)
all_data$y=as.numeric(all_data$y=="yes")
train=all_data %>% 
filter(data=='train') %>% 
select(-data) 
```

```{r}
finalmnth=round(prop.table(table(all_data$month,all_data$y),1)*100,1)
sss=addmargins(finalmnth,2)
sort(sss[,1])
all_data=all_data %>% 
mutate(month_1=as.numeric(month %in% c("aug","jun","nov","jan","jul")),month_2=as.numeric(month %in% c("dec","sep")),month_3=as.numeric(month=="mar"),month_4=as.numeric(month=="oct"),month_5=as.numeric(month=="apr"),
month_6=as.numeric(month=="feb")) %>% 
select(-month)
```

```{r}
test=all_data %>% 
filter(data=='test') %>% 
select(-data,-y)
aa=lm(y~.,data=train)
summary(aa)
```


```{r}
www=lm(y~.-edu_sec,data=train)
summary(www)
fit_train=train %>% select(-edu_sec)
colnames(fit_train)
fit=glm(y~.,family = "binomial",data=fit_train)
summary(fit) 

```






```{r}
final=glm(y~housing + loan + campaign + id + euribor3m+ job_4 + job_5 + divorced + single + edu_primary + co_cellular + co_tel + month_1 + month_2 + month_3 + month_4 + month_5 + month_6 + poc_success + poc_failure + poc_other+cons.price.idx+cons.conf.idx+pdays ,data=fit_train,family="binomial")
summary(final)

```
```{r}
train$score=predict(fit_final,newdata = train,type="response")
test$score=predict(fit_final,newdata =test,type = "response")
x=0.113318
test$left=as.numeric(test$score>x)
table(test$left)
```


```{r}
test$leftfinal=factor(test$left,levels = c(1,0),labels=c("yes","no"))
table(test$leftfinal)
write.csv(test$leftfinal,"kkk.csv")
```

